### PR TITLE
added PSI-MOD contents from sourceforge cvs …

### PR DESCRIPTION
**Pull request by mwalzer**
for fixing links and future reference to a dedicated repository.

### CODE REVIEW

**Comment by mwalzer** [comment]
There is one file missing I wasn't able to procure from any of the PSI repositories, called PSI_MS_mod_nomenclature.xls. It is supposed to be [here](http://psidev.sourceforge.net/mod/ms/PSI_MS_mod_nomenclature.xls)

**Comment by mwalzer** [comment]
We probably also want to change links on the PSI website, the ontology lookup and tools?

**Comment by mwalzer** [comment]
Is there something else missing for legacy support?

**Comment by ypriverol** [comment]
@mwalzer, where do these files obo.xml, come from. We can probably store only the .obo file? .

**Comment by ypriverol** [comment]
@mwalzer I can accept the PR if you want.

**Comment by mwalzer** [comment]
So the obo files come from the cvs where all(?) the psi xml files were linking to if they used it
http://psidev.cvs.sourceforge.net/viewvc/*checkout*/psidev/psi/mod/data/psi-mod.obo

**Comment by mwalzer** [comment]
It is basically a copy of the CVS folder from SourceForge

**Pull request merged**
