### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by cthoyt**
This pull request is part of an initiative to make the licensing information about OBO Foundry ontologies more actionable.

While this ontology contains licensing information in its metadata, GitHub is not aware of the license unless you create a `LICENSE` file with standardized text. This PR creates a `LICENSE` file with the standard text for the CC BY 4.0 license. 

More information about this initiative and further discussion is taking place here: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1840.

### CODE REVIEW

**Review by edeutsch — APPROVED** [review]
Thanks Charles, also tagging @mobiusklein @pabinz @ricardblum for review.

**Review by mobiusklein — APPROVED** [review]
I can't find a reference to an existing license in the text of the repository. Assuming the original authors/owners are fine with the CC4 license, this looks right to me.

**Comment by cthoyt** [comment]
This was what was written in the OBO foundry

**Comment by pabinz** [comment]
Fine for me

**Review by pabinz — APPROVED** [review]
FIne

**Pull request merged**
