### PR TITLE
Trimethyl and formal charges

### PR DESCRIPTION
**Pull request by rfellers**
I've stumbled across multiple trimethylations that have both a formal charge of +1 and a mass ~42 Da. Shouldn't those be changed  to have a mass ~43 Da?

Also, other trimethylations have a mass ~42 Da with no formal charge (e.g. MOD:00430, MOD:01669). Should these 2 also be changed to a formal charge of +1 and a mass ~43 Da? If so, I'm happy to update my branch so these changes come in with this PR.

Thanks!

### CODE REVIEW

**Comment by edeutsch** [comment]
I'm in water over my head here, but my reading of the definition of the first one, MOD:00855:

comment: For amino acids residues, amine trimethylation can effectively only be accomplished with an aminium, protonated primary amino, group. This process accounts only for trimethylation and not protonation. The al
ternative N6Me3+Lys process (MOD:00083) accounts for both protonation and trimethylation.

suggests that this mod starts from a protonated alanine and ends with a protonated trimethylated alanine so there is no additional proton so the +42 is correct? MOD:00083 is the +43 you're looking for?

??
I'm not sure at all.

**Comment by pmt706** [comment]
I'll take a look at it and let you all know.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rfellers** [comment]
Thanks @pmt706. Ya, I'm in the same boat as @edeutsch, but perhaps the water is even higher over my head! (those 2 metaphors don't work the best together, but you get it).

**Comment by pmt706** [comment]
So, Ryan and I just spoke about this and @edeutsch, you were on the right path.  The majority of the proposed changes were from a misunderstanding related to the "origin" amino acid.  In most of those cases, the origin was already protonated, making the mass change 42.xxx instead of 43.xxx as stated originally.  We did discover that one entry was still missing a formal charge, so that should be added in.  I think the vast majority of use cases for PSI-MOD will never use these more esoteric ways to define amino acid modifications (from the protonated AA), but trimethylation will always be "weird" because it brings its formal charge along for the ride.

**Comment by pmt706** [comment]
Unless @pabinz or @ricardblum has any major concerns, I'll merge this PR soon.

**Review by edeutsch — APPROVED** [review]
The PR now seems good to merge.

**Comment by ricardblum** [comment]
Hi All,

No concern from my side, and sorry for this delayed answer but we are 
really overwhelmed by the increase in Covid-19 cases in Lyon, and the 
consequences on the organization of teaching at the University.

Best,

Sylvie.

Professor Sylvie RICARD-BLUM
Pericellular and Extracellular Supramolecular Assemblies
UMR 5246 CNRS - University Lyon 1
Institute of Molecular and Supramolecular Chemistry and Biochemistry
University Claude Bernard Lyon 1, 43 Boulevard du 11 novembre 1918
69622 Villeurbanne Cedex, France
Phone: +33(0)4 72 44 82 32
E-mail: sylvie.ricard-blum@univ-lyon1.fr
http://www.icbms.fr
The French Society for Matrix Biology http://www.sfbmec.fr
The International Society for Matrix Biology http://ismb.org

Le 02/10/2020 à 21:08, pmt706 a écrit :

**Pull request merged**
