### PR TITLE
Adding xrefs to UniProt's PTMList and publishing our first OWL

### PR DESCRIPTION
**Pull request by pmt706**

### CODE REVIEW

**Comment by pmt706** [comment]
This adds crossrefs to the UniProt [PTMList](https://www.uniprot.org/docs/ptmlist) (which has listed some xrefs to PSI-MOD).  There are incorrect links on both sides that will be addressed once this first crossreference task is done.

**Comment by edeutsch** [comment]
What kind of review do you think it appropriate here? The diffs under [Files changed] are too big to display. I would need to start pulling down your fork and comparing, and honestly I wouldn't know a good owl file if I saw one.

**Comment by pmt706** [comment]
Well, That's a good question. I think the best way to check for a well-formed OWL file would be to open it in something like [Protege](https://protege.stanford.edu/products.php) and make sure the file opens without error.  The other thing that's in this PR is the XREFs, but those are just 1:1 with UniProt, so again, as long as the OBO/OWL opens in Protege, then I didn't mess up any of the formatting.

**Comment by pmt706** [comment]
(and I know from experience, that syntax errors will cause the ROBOT Tool/Protege to crash or not open a file with often very poor tracing of where the exact offending line is!)

**Review by pmt706 — COMMENTED** [review]
It opens in Protege for me without error and the XRefs are correct, so can we merge this (so that I can get ontobee updated/etc?)

**Comment by edeutsch** [comment]
sure, go ahead and merge. I haven't been able to examine it, but am swamped at the moment, so go ahead. If there is a problem, we can do corrections later. Thanks!

**Pull request merged**
